---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

conda_dir: /opt/conda

nvm:
  path: /opt/nvm

uomi:
  validator:
    source_url: https://github.com/Uomi-network/uomi-node/releases/download
    ports:
      rpc_port: 9946
      p2p_port: 30335
      prometheus_port: 9617
  ai:
    source_url: https://github.com/Uomi-network/uomi-node-ai.git
    conda:
      source_url: https://repo.anaconda.com/miniconda
