---
- name: Set up Uomi AI service
  hosts: all
  become: true
  gather_facts: true
  vars:
    allowed_node_types: [ai]
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
    - group_vars/default.yml
    - group_vars/{{ env }}.yml

  pre_tasks:
    - name: Setup environment
      when: type in allowed_node_types
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml

  tasks:
    - name: Run ai role
      when: type in allowed_node_types
      block:
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include ai role
          ansible.builtin.include_role:
            name: ai
