---
# maintains directories and paths
node_home_dir: /opt/{{ service_identifier }}

node_bin_dir: "{{ node_home_dir }}/bin"
node_config_dir: "{{ node_home_dir }}/config"
node_data_dir: "{{ node_home_dir }}/data"
node_log_dir: "{{ node_home_dir }}/log"
node_key_dir: "{{ node_home_dir }}/key"

node_directories:
  - "{{ node_home_dir }}"
  - "{{ node_bin_dir }}"
  - "{{ node_config_dir }}"
  - "{{ node_data_dir }}"
  - "{{ node_key_dir }}"
  - "{{ node_log_dir }}"

node_genesis_file_path: "{{ node_config_dir }}/{{ node_genesis_file_name }}"
node_log_file_path: "{{ node_log_dir }}/{{ service_identifier }}.log"
