---
- name: Set ownership for bin directory
  ansible.builtin.file:
    path: "{{ ai_bin_dir }}"
    owner: root
    group: root
    recurse: true

- name: Clone the repository
  ansible.builtin.git:
    repo: "{{ uomi.ai.source_url }}"
    dest: "{{ ai_bin_dir }}"
    version: "{{ uomi.ai.version }}"
    force: true
  notify:
    - Restart service

- name: Set ownership for bin directory
  ansible.builtin.file:
    path: "{{ ai_bin_dir }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true
