---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ ai_home_dir }}"
    directories: "{{ ai_directories }}"
    log_file_path: "{{ ai_log_file_path }}"

- name: Include prepare env task
  ansible.builtin.include_tasks: prepare_env.yml
  when: prepare_env | default(false) | bool

- name: Clone the repository
  ansible.builtin.git:
    repo: "{{ uomi.ai.source_url }}"
    dest: "{{ ai_bin_dir }}"
    version: "{{ uomi.ai.version }}"
    force: true
  become: true
  become_user: "{{ service_identifier }}"
  notify:
    - Restart service

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
