---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ ai_home_dir }}"
    directories: "{{ ai_directories }}"
    log_file_path: "{{ ai_log_file_path }}"

- name: Include prepare task
  ansible.builtin.include_tasks: prepare.yml

- name: Copy systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
